services:
  - type: web
    name: crisis-app-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
